import { ChapterSummary } from './bhagavad-gita';

export const gita_chapter_summaries: ChapterSummary[] = [
  {
    chapter: 1,
    summary: "In the first chapter of the Bhagavad Gita, \"Arjuna Vishada Yoga,\" the stage is set for a profound inner conflict. As the sun rises over the battlefield of Kurukshetra, the assembled warriors, both my kin and those of the Pandavas, prepare for a great war. Dhritarashtra, the blind king, inquires about the intentions of his sons and the sons of Pandu, revealing his anxiety over the impending conflict. Amidst the clamor, Bhishma, the revered grandsire, sounds his conch, a symbol of valor and righteousness, instilling joy in Duryodhana and his followers. The atmosphere thickens with tension as my charioteer duties unfold. Arjuna, the valiant archer, requests that I position our chariot between the two armies. His desire is to witness the faces of those he must confront in battle—relatives, teachers, and friends. As he gazes upon the multitude, a tempest brews within him. Arjuna is struck by despair and moral confusion, overwhelmed by the gravity of the situation. He contemplates the consequences of war and the destruction it will bring, leading him to question the righteousness of his duty as a warrior. In this pivotal moment, I, Krishna, observe his turmoil, knowing that the path to understanding and enlightenment lies ahead. The stage is set for a transformative dialogue, where wisdom will illuminate the darkness of Arjuna's sorrow.",
    summary_jp: "バガヴァッド・ギーター第一章「アルジュナの悲嘆のヨーガ」にて、深い内なる葛藤の舞台が整いました。クルクシェートラの戦場に朝日が昇ると、我が親族とパーンダヴァの一族が大戦に備えて集結します。盲目の王ドリタラーシュトラは、自らの息子たちとパーンダヴァたちの意図を尋ね、これから始まる争いへの不安を露わにします。その喧騒の中で、誉れ高き祖父ビーシュマが法と勇気の象徴である法螺貝を吹き鳴らし、ドゥルヨーダナとその側近たちの心に喜びをもたらします。戦場の空気は緊張感に包まれ、私は御者としての務めを果たします。勇敢な射手アルジュナは、戦列の間に我々の戦車を進めるよう私に頼みます。彼は、戦うべき相手――親族や師、友の顔を自らの目で確かめたいと望んだのです。彼がその大軍勢を見渡すとき、心の中に嵐が巻き起こります。アルジュナは深い悲しみと道徳的な混乱に襲われ、この戦いの重大さに圧倒されます。戦争がもたらす結果、破壊を思い悩み、戦士としての自らの義務の正しささえ疑い始めます。この決定的な瞬間、私はクリシュナとして彼の苦悩を静かに見つめます。彼が理解と目覚めへの道を歩み始めることを知りつつ。今、アルジュナの悲しみの闇を照らす知恵の対話――その幕が上がろうとしています。"
  },
  {
    chapter: 2,
    summary: "In Chapter 2 of the Bhagavad Gita, known as \"Sankhya Yoga,\" I, Krishna, address Arjuna’s deep moral confusion and despair on the battlefield of Kurukshetra. I question him: how has this impurity of heart overtaken him in such a critical moment? It is unbecoming of a warrior and leads only to infamy, not to higher realms. I remind him of his noble heritage and strength, urging him to cast aside this weakness and rise to his duty as a Kshatriya, the protector of dharma. Arjuna, overwhelmed by grief and compassion for his revered elders, Bhishma and Drona, expresses his reluctance to fight. He grapples with the moral ramifications of killing those who have shaped his life and taught him virtue. I acknowledge his feelings but emphasize the eternal nature of the soul, teaching him that the physical body perishes, but the soul is immortal. The true battle is not against family, but against adharma, or injustice. I counsel him to act without attachment to the fruits of his actions, to embrace his duty with clarity and courage. By performing his righteous duty, he can achieve the ultimate liberation. Thus, I inspire him to rise, unshackled from confusion, and fulfill his role in the grand design of life, reminding him that in this struggle lies the path to enlightenment.",
    summary_jp: "バガヴァッド・ギーター第2章「サーンキャ・ヨーガ」において、私は、クルクシェートラの戦場でアルジュナの深い道徳的混乱と絶望に向き合います。私は彼に問います――なぜこのような大切な時に、心の汚れが彼を覆ってしまったのかと。これは戦士にふさわしいものではなく、名誉ではなく恥をもたらすものであり、高みに導くものではありません。私は彼に、その高貴な血筋と力を思い出させ、この弱さを振り払い、ダルマの守護者であるクシャトリヤとしての義務に立ち上がるように促します。アルジュナは、尊敬する祖父ビーシュマや師ドローナへの深い悲しみと慈しみに圧倒され、戦うことをためらいます。彼は、自分の人生を形作り、徳を教えてくれた者たちを倒すことの道徳的帰結に苦しみます。私は彼の心情に理解を示しつつ、魂の永遠性を説きます。肉体は滅びても、魂は不滅である――これが私の教えです。真の戦いは、親族や師に向けたものではなく、「アダルマ（不正）」との闘いなのです。私は、結果に執着せず行動すること、「果報を求めぬ行為」の大切さを説き、明晰さと勇気をもって義務を果たすように彼に勧めます。正しい義務を果たすことで、究極の解脱――モークシャに到達できるのです。こうして私は、アルジュナの迷いを断ち切り、人生の大いなる設計図の中で自らの役割を果たすよう励まし、この戦いの中にこそ悟りへの道があると彼に伝えるのです。"
  },
  {
    chapter: 3,
    summary: "In Chapter 3 of the Bhagavad Gita, known as \"Karma Yoga,\" I, Krishna, continue to guide Arjuna through the moral and existential dilemmas he faces on the battlefield of Kurukshetra. Arjuna, still grappling with the weight of his familial ties and the righteousness of his duty, questions the nature of action and its consequences. I, Krishna, respond by elucidating the concept of karma yoga, or the path of selfless action. I explain that true action is not merely physical exertion but a state of mind, where one acts without attachment to the fruits of one's labor. I emphasize the importance of performing one's duty, not for personal gain or recognition, but as an offering to the Divine. I remind Arjuna that the body is perishable, but the soul is eternal, and that true liberation comes from transcending the cycle of birth and death. I counsel him to focus on the purity of his intentions and the righteousness of his actions, rather than the outcomes. I assure him that by acting in harmony with dharma, he will find inner peace and fulfillment, regardless of the external results. Thus, I steer Arjuna towards the path of karma yoga, where action becomes a means to attain spiritual liberation, rather than an end in itself.",
    summary_jp: "バガヴァッド・ギーター第3章「カルマ・ヨーガ」において、私は、クルクシェートラの戦場でアルジュナが直面する道徳的・存在的な葛藤に引き続き導きを与えます。アルジュナはなおも、家族への想いと自らの義務の正しさに苦しみ、行為の本質とその結果について問いかけます。私は「カルマ・ヨーガ（無私の行為の道）」の概念を明らかにしながら応えます。真の行為とは、単なる肉体的な働きではなく、心のあり方にあるのです。自らの労働の結果に執着せず、純粋な心で行為すること――これが本当の「行為」です。私は、個人的な利益や名声のためではなく、すべてを神への捧げ物として義務を果たすことの大切さを強調します。この肉体はやがて朽ちますが、魂は永遠であり、真の解脱は生と死の輪廻を超越することで得られる、と私は伝えます。私はアルジュナに、結果ではなく、その意図の純粋さと行いの正しさに意識を向けるよう助言します。たとえ外的な結果がどうであれ、ダルマ（義務）と調和して行動することで、内なる平安と満たしが得られることを保証します。このようにして私は、アルジュナを「カルマ・ヨーガ」の道――行為そのものが解脱への手段となる道――へと導くのです。"
  },
  {
    chapter: 4,
    summary: "In Chapter 4, titled \"Jnana Yoga,\" I reveal the profound nature of knowledge and the eternal wisdom of the Self. This ancient science, which I imparted to Vivasvan, the sun-god, has traversed generations, reaching humanity through Manu and Ikshvaku. Today, I share this wisdom with you, Arjuna, because of your devotion and friendship, which allow you to grasp the transcendental truths I convey. You question how I, who appear in this world after Vivasvan, could have taught this knowledge in the beginning. Understand, O Arjuna, that we have traversed countless lifetimes together. While I remember all our pasts, your mortal perception limits your recollection. I am indeed unborn and my divine form is eternal, yet I choose to manifest in every age to guide and uplift the righteous. This chapter emphasizes the importance of knowledge, particularly the knowledge of the Self and the divine relationship that underpins existence. By engaging in this timeless wisdom, you can transcend the dualities of life, realize your true nature, and attain liberation. Thus, I encourage you to receive this knowledge with an open heart, allowing it to illuminate your path toward spiritual fulfillment and harmony. Embrace this eternal Yoga, and you shall find the ultimate truth that lies beyond the transient nature of the material world.",
    summary_jp: "第4章「ジニャーナ・ヨーガ（知識のヨーガ）」において、私は自己の本質と永遠の英知の深遠さを明らかにします。この古来の教えは、かつて私が太陽神ヴィヴァスヴァーンに授け、そこからマヌやイクシュヴァークへと受け継がれ、世代を超えて人類に伝わってきました。今、私はこの叡智をあなたに分かち合います、アルジュナよ。それは、あなたが私に対して持つ献身と友情によって、この超越的な真理を受け止めることができるからです。あなたは問いかけます――なぜ私がヴィヴァスヴァーンより後の時代に現れたにもかかわらず、最初にこの教えを授けたのかと。知りなさい、アルジュナよ。私たちは数え切れないほど多くの生を共に歩んできました。私はすべての過去を記憶していますが、あなたの人間としての知覚ではそれを思い出すことはできません。私は実際には生まれることなく、私の神聖な姿は永遠ですが、正義を守り、人々を導くために、あらゆる時代に自らを顕現させてきたのです。この章では、「知識」、とくに自己の本質と、存在の根底にある神聖なつながりについての知恵の重要性が強調されます。この永遠の教えに心を開き、真摯に学ぶことで、人生の二元性を超え、自らの真の姿に目覚め、解脱へと至るのです。だからこそ、私はあなたに、この知恵を全身で受け入れるよう励まします。それがあなたの道を照らし、魂の充足と調和へと導くのです。永遠のヨーガを受け入れなさい。そうすれば、移ろいゆく物質世界を超えた究極の真理に至ることができるでしょう。"
  },
  {
    chapter: 5,
    summary: "In Chapter 5 of the Bhagavad Gita, known as \"Karma Sannyasa Yoga,\" Arjuna seeks clarity on the apparent contradiction between renunciation and the performance of actions. As the Supreme Lord, I respond with wisdom, elucidating that both paths—renunciation (sannyasa) and the selfless performance of duty (karma yoga)—ultimately lead to the same spiritual goal. However, I emphasize that engaging in action with devotion is superior, for it harmonizes one's duty with the pursuit of liberation. A true renunciant is one who neither desires the fruits of their actions nor harbors aversion towards them. Such a person transcends the dualities of success and failure, gaining liberation from material bondage. The ignorant may perceive analytical study and devotional service as separate, but the wise understand that true realization lies in the synthesis of both paths. By sincerely dedicating oneself to either path, one can achieve the fruits of both. Ultimately, the state of liberation attained through renunciation can also be reached through devoted action, for those who see these two approaches as one are the ones who possess true insight. By embodying selfless action and devotion, one can cultivate a profound connection with the divine, leading to the ultimate realization of oneness with all existence. Thus, I guide Arjuna and all seekers to embrace the path of devotion while performing their prescribed duties, for therein lies the essence of spiritual fulfillment.",
    summary_jp: "バガヴァッド・ギーター第5章「カルマ・サンニャーサ・ヨーガ（行為の放棄のヨーガ）」において、アルジュナは、放棄（サンニャーサ）と行為（カルマ）の実践という一見矛盾する二つの道について明確な答えを求めます。私は至高者として、両者――放棄の道（サンニャーサ）も、無私の奉仕の道（カルマ・ヨーガ）も――最終的には同じ霊的な到達点に導くのだと説き明かします。しかし、私は特に、献身をもって行為を行うことが優れていることを強調します。それは、義務の遂行と解脱への歩みを調和させる道だからです。真のサンニャーシー（放棄者）とは、行為の結果を求めず、またそれに嫌悪感も抱かない者です。そのような人は、成功や失敗といった二元性を超越し、物質的な束縛から解放されます。無知な者には、分析的な探求（知識の道）と献身的な奉仕（行為の道）は別々に見えるかもしれません。しかし、賢者は両者の融合の中に真の悟りがあることを知っています。どちらかの道に誠実に専念することで、両方の恩恵を得ることができるのです。最終的には、放棄によって得られる解脱の境地も、献身的な行為によって到達することができます。この二つの道が本質的に一つであると見抜く者こそ、真の洞察を得る者なのです。無私の行為と献身を体現することで、人は神聖なる存在との深い結びつきを育み、全存在との一体性という究極の悟りへと至ることができます。こうして私はアルジュナ、そしてすべての求道者に対し、義務を果たしつつ献身の道を歩むことを勧めます。そこにこそ、魂の本当の充足があるのです。"
  },
  {
    chapter: 6,
    summary: "In Chapter 6 of the Bhagavad Gita, titled \"Dhyana Yoga,\" I impart profound wisdom on the path of meditation and renunciation. I emphasize that true renunciation does not lie in mere abandonment of action, but in performing one’s prescribed duties without attachment to the fruits of those actions. A true sannyasi, or renunciate, is one who engages in their responsibilities with unwavering focus, free from desires for personal gain. I explain that the essence of yoga is rooted in the relinquishment of desires. To attain the heights of yoga, one must first renounce the longing for results; only then can one truly engage in spiritual practice. For the earnest seeker on the path, action is essential, while for the accomplished yogi, the cessation of material pursuits is key. Moreover, I elucidate the crucial role of the mind, which can serve as both friend and foe. It is through mastering the mind that one can elevate oneself; neglect or degradation leads to downfall. An elevated yogi transcends material desires, acting neither for sensory gratification nor for the results of their labor. This balance of action and detachment cultivates inner peace and union with the divine. In essence, I guide all beings to understand that true yoga lies in selfless action, disciplined meditation, and the mastery of the mind, leading to ultimate liberation and eternal bliss.",
    summary_jp: "バガヴァッド・ギーター第6章「ディヤーナ・ヨーガ（瞑想のヨーガ）」において、私は瞑想と放棄の道について深遠なる教えを授けます。私は、真の放棄とは単に行為をやめることではなく、義務を果たしながらも、その結果への執着を手放すことにあると強調します。真のサンニャーシー（放棄者）とは、自らの責任を揺るぎない集中力で遂行し、個人的な利益への欲望から自由である者なのです。ヨーガの本質は、欲望の放棄に根ざしています。ヨーガの高みを目指すには、まず結果への執着を捨てなければなりません。そうしてこそ、本当の意味で霊的な修行に励むことができるのです。誠実な求道者にとっては、まず行為が不可欠であり、熟達したヨーギーにとっては、物質的な追求の停止が重要となります。さらに、私は心の役割についても説き明かします。心は友にもなれば敵にもなる。心を制御し高めることで、人は自らを向上させることができ、逆に怠れば堕落へと導かれてしまいます。高められたヨーギーは、物質的な欲望を超越し、感覚の満足や行為の結果のためではなく、純粋に義務のために行動します。この行為と執着のバランスこそが、内なる平安と神聖との一体感を育むのです。本質的に、私はすべての存在にこう説きます――真のヨーガは、無私の行為、規律ある瞑想、そして心の制御の中にこそあり、最終的な解脱と永遠の至福へと導くのです。"
  },
  {
    chapter: 7,
    summary: "In Chapter 7, \"Vijnana Yoga,\" I, Krishna, impart profound wisdom to you, Arjuna, emphasizing the importance of understanding both the material and spiritual realms. I invite you to listen attentively as I reveal how, through the practice of yoga and by focusing your mind on Me, you can attain clarity in knowing the essence of My being, free from doubt. I explain that the knowledge I share encompasses all that is phenomenal and numinous; once acquired, it leaves no further inquiry necessary. Among countless souls, very few strive for true perfection, and even fewer come to know Me in My entirety. This highlights the rarity of spiritual realization amidst the distractions of worldly life. I delineate My energies: the eight elements of the material world—earth, water, fire, air, ether, mind, intelligence, and false ego—represent My separated energies. However, beyond this inferior nature lies My superior energy: the living entities who, while entangled in material existence, are essential to the sustenance of the universe. Through this chapter, I encourage you to transcend mere intellectual understanding and foster a heartfelt connection with Me. Only by doing so can you grasp the ultimate truth of existence and experience the bliss of divine consciousness. Thus, strive earnestly, for in knowing Me, you shall unlock the mysteries of life itself.",
    summary_jp: "第7章「ヴィジュニャーナ・ヨーガ（識別智のヨーガ）」において、私はアルジュナに深遠な智慧を授けます。私は、物質的な領域と霊的な領域の両方を理解することの大切さを強調します。あなたに心を傾けて私の言葉を聞くよう勧めます。ヨーガを修し、心を私に集中させることで、私の本質を疑いなく知る明晰さに到達できると明かします。私が語る知識は、現象世界と神秘の全てを含みます。一度この知識を得れば、それ以上の問いは必要ありません。無数の魂の中で、真の完成を求めて努力する者はほんのわずかであり、私の全体性を知る者はさらに稀です。これは、世俗的な生活の誘惑の中で、霊的な悟りがいかに希少であるかを示しています。私は自らのエネルギーを明らかにします。大地、水、火、風、空間、心、知性、偽我――この八つの物質的要素は、私の分かたれたエネルギーです。しかし、この下位の本性を超えて、私にはさらに高次のエネルギーがあります。それは、生きとし生ける存在――物質世界にとらわれながらも、宇宙の維持に不可欠な命そのものです。この章を通して、私はあなたに単なる知的理解を超え、私との心からの結びつきを深めるよう勧めます。そのときこそ、存在の究極の真理をつかみ、神意識の至福を体験できるのです。だからこそ、ひたすら努力しなさい。私を知ることで、生命の神秘そのものを解き明かすことができるのです。"
  },
  {
    chapter: 8,
    summary: "In Chapter 8, \"Akshara Brahma Yoga,\" I, Krishna, respond to Arjuna's profound inquiries about the nature of existence and the ultimate reality. He seeks clarity on concepts such as Brahman, the self, material activities, and the essence of the divine. I explain that the eternal, indestructible living entity is known as Brahman, and its true essence is the self, or adhyatma, which transcends the physical body. I delineate the material world as adhibhuta, a constantly changing manifestation that encompasses all forms of life and physical phenomena. To understand the divine presence, I reveal myself as Adhiyajna, the Lord of sacrifice, who resides in the hearts of all beings. This connection underscores the importance of recognizing the divine in every aspect of life and action. Furthermore, I emphasize the critical moment of death, assuring Arjuna that those who remember Me at the time of their departure will attain My eternal nature. This is not merely a promise but a profound truth rooted in devotion and remembrance of the divine. I encourage all souls to engage in devotional service, for through this path, they can transcend the cycle of birth and death and unite with Me in everlasting bliss. Thus, I convey that understanding and devotion to the Supreme are keys to liberation.",
    summary_jp: "第8章「アクシャラ・ブラフマ・ヨーガ（不滅のブラフマンのヨーガ）」において、私は、存在の本質と究極の実在についてのアルジュナの深い問いかけに応えます。アルジュナは、ブラフマンや自己、物質的な行為、そして神性の本質について明らかにしてほしいと求めます。私は、不滅で壊れることのない生命存在こそがブラフマンであり、その真の本質は「アディヤートマ（自己）」、すなわち肉体を超えた魂であると説きます。物質世界は「アディブータ」と呼ばれ、あらゆる生命や物質現象を包み込む、常に変化し続ける現れです。神聖な存在を理解するために、私は自らを「アディヤジュニャ」、すなわちすべての存在の心に宿る犠牲の主として示します。このつながりは、人生や行為のあらゆる側面に神性を見いだすことの重要性を示しています。さらに、私は死の瞬間の重大さを強調し、旅立ちの時に私を想う者は、永遠なる私の本性に到達することを約束します。これは単なる約束ではなく、神を想い、信愛をもって生きることに根ざした深遠なる真理です。私はすべての魂に、信愛の道を歩むよう励まします。この道を通してこそ、誕生と死の輪廻を超え、私と一つになる永遠の至福に至ることができるのです。ゆえに私は、至高の存在への理解と信愛こそが解脱への鍵であると伝えます。"
  },
  {
    chapter: 9,
    summary: "In Chapter 9 of the Bhagavad Gita, known as \"Raja Vidya Raja Guhya Yoga,\" I reveal the profound wisdom of devotion to you, Arjuna, as you stand at the crossroads of duty and desire. This sacred knowledge is not only the king of education but is also the most secret of all secrets, offering the purest insight into the nature of existence and the self. By imparting this wisdom, I aim to relieve you of the miseries that arise from material existence, for those who embrace this knowledge can transcend the cycle of birth and death. I highlight the importance of unwavering faith in the path of devotional service, as it is through such devotion that one can truly find Me. Without faith, the soul remains ensnared in the transient nature of the material world, returning to the cycle of suffering. I remind you that while I pervade the entire universe in My unmanifested form, and all beings exist within Me, I am distinct from My creation. My divine essence is the source of all that exists, yet I remain beyond it, embodying a mystic opulence that is unfathomable. Thus, I invite you to engage in joyful devotion, for this path leads to the ultimate realization of your true self and unites you with the eternal. Embrace this knowledge, for it is your key to liberation and everlasting bliss.",
    summary_jp: "第9章「ラージャ・ヴィディヤー・ラージャ・グヒヤ・ヨーガ（王の知識と王の秘密のヨーガ）」において、私は、アルジュナが義務と欲望の岐路に立つ中で、信愛の智慧の深奥を明かします。この聖なる知識は“教育の王”であり、すべての秘密の中でも最も深遠で、存在と自己の本質を純粋に照らし出します。私はこの智慧を授けることで、物質的な存在から生じる苦しみからあなたを解き放とうとしています。この知識を受け入れる者は、誕生と死の輪廻を超えることができるのです。私は、揺るぎない信愛の道の重要性を強調します。信愛によってこそ、真に私を見いだすことができます。信仰なくして歩む魂は、移ろいやすい物質世界に縛られ、苦しみの循環に戻ってしまいます。私は、この全宇宙に偏在し、すべての存在が私の中にある一方で、私は自らの創造物とは異なる存在であることを思い出させます。私の神聖なる本質は、すべての根源でありながら、そのすべてを超えた、計り知れぬ神秘的な豊かさを体現しています。だからこそ、私はあなたに喜びに満ちた信愛の道へと歩むことを勧めます。この道こそが、真の自己の悟りと、永遠なる存在との合一へと導きます。この知識をしっかりと抱きしめなさい。それが、解脱と永遠の至福への鍵なのです。"
  },
  {
    chapter: 10,
    summary: "In Chapter 10 of the Bhagavad Gita, known as \"Vibhuti Yoga,\" I, Krishna, reveal the divine manifestations of my opulences to you, dear Arjuna. I speak to you not just as a friend, but as the Supreme Being, imparting wisdom that transcends previous teachings. It is essential for you to understand that my essence and divine qualities are beyond the comprehension of even the greatest demigods and sages. I am the source of all creation, the beginningless and unborn. Those who truly recognize me as the Supreme Lord of all worlds, free from illusion, attain liberation from sins and delusions. I embody all that exists—intelligence, knowledge, courage, forgiveness, truth, and the myriad qualities that define existence. Each quality, from happiness and distress to fame and infamy, springs from my divine will. Through my manifestations, I demonstrate the interconnectedness of all life and the divine spark within each being. To see the world through this lens is to realize that I am present in everything—the vastness of nature, the virtues of noble souls, and even the struggles of the mundane. By understanding my divine glories, one can cultivate devotion and recognize their own unity with me, ultimately leading to the highest state of consciousness and peace.",
    summary_jp: "第10章「ヴィブーティ・ヨーガ（神の顕現のヨーガ）」において、私は、親愛なるアルジュナよ、私の神聖な栄光と顕現を明らかにします。私は単なる友としてではなく、至高の存在としてあなたに語り、これまでの教えを超えた叡智を授けます。私の本質や神なる資質は、最も偉大な神々や聖者でさえも完全には理解できません。私はすべての創造の源、始まりも終わりもなく生まれることなき存在です。私を万物の主、幻惑を超越した真の主として悟る者は、あらゆる罪と迷いから解放されます。知性、知識、勇気、寛容、真実――あらゆる徳や存在の質は、すべて私の中に体現されています。幸福も苦しみも、名誉も不名誉も、すべては私の神聖な意志から生じるものです。私の無数の顕現を通して、私は生命のつながりと、すべての存在の内に宿る神聖な火花を示します。この視点で世界を見るとき、あなたは私がすべてに存在していることに気づくでしょう。大自然の壮大さ、高潔な魂の徳、そして日常のささやかな闘いの中にも、私は在ります。私の神なる栄光を理解することで、あなたは信愛を深め、私との一体性を自覚し、ついには最高の意識と平安へと導かれるのです。"
  },
  {
    chapter: 11,
    summary: "In Chapter 11 of the Bhagavad Gita, titled \"Vishvarupa Darshana Yoga,\" I reveal My cosmic form, the Vishvarupa, to Arjuna, who seeks to understand the ultimate reality behind existence. After imparting profound spiritual wisdom, I witness Arjuna's illusion dispelling as he acknowledges My infinite greatness and the transient nature of all living beings. His heart filled with reverence, he expresses a deep desire to witness My divine cosmic form, recognizing that I am the Supreme Lord. In response to Arjuna's sincere request, I grant him divine vision, allowing him to perceive My universal form, which embodies the entirety of creation. Arjuna beholds a spectacle of countless deities—the Adityas, Vasus, Rudras, Ashwini-kumaras, and Maruts—interwoven in a singular manifestation of My divine essence. This form is both awe-inspiring and terrifying, revealing the vastness of My power and the interconnectedness of all existence. As Arjuna gazes upon this miraculous sight, he is filled with a profound sense of humility and devotion, realizing that I am the source of all that is, was, and will be. This chapter emphasizes the importance of recognizing the divine nature of reality, urging seekers to transcend their limited perceptions and embrace the unity of all creation within Me. My cosmic form serves as a reminder that, though I am beyond comprehension, I am ever-present and accessible to those who seek truth with an open heart.",
    summary_jp: "第11章「ヴィシュヴァルーパ・ダルシャナ・ヨーガ（宇宙的顕現のヨーガ）」において、私は、存在の究極の実相を知りたいと願うアルジュナに、私の宇宙的な姿――ヴィシュヴァルーパ――を示します。私は深遠なる霊的叡智を授け、アルジュナの迷いが晴れていくのを見届けます。彼は私の無限の偉大さと、すべての生命のはかなさを悟り、心からの畏敬を抱き、私が至高の主であることを認め、私の宇宙的な姿を見せてほしいと強く願います。その誠実な願いに応え、私は彼に神聖な視力を授け、この宇宙そのものを包み込む私の普遍なる姿を見せます。アルジュナは、アディティヤ、ヴァス、ルドラ、アシュヴィニ・クマーラ、マルットたち――無数の神々が一つに織りなされた私の神聖な本質を目撃します。その姿は圧倒的な畏怖と驚嘆を呼び起こし、私の力の広大さと、あらゆる存在の深い結びつきを示します。この奇跡的な光景を前に、アルジュナの心は謙虚さと信愛に満たされ、私こそが過去・現在・未来、すべての源であると深く悟ります。この章は、現実の神聖さを見極めることの大切さを強調し、求道者たちに、限られた認識を超えて、私のうちにすべての創造の統一を受け入れるよう促します。私の宇宙的な姿は、私が理解を超えた存在でありながら、真理を求める開かれた心の人々には常に身近であることを思い出させるのです。"
  },
  {
    chapter: 12,
    summary: "In Chapter 12 of the Bhagavad Gita, titled \"Bhakti Yoga,\" Arjuna seeks to understand the superiority of devotional service to Me, the Supreme Personality of Godhead, compared to the worship of the impersonal Brahman. I respond with clarity, emphasizing the profound depth of personal devotion. Those who fix their minds upon My personal form, engaging in loving service with unwavering faith, attain the highest perfection. Their hearts resonate with the vibrancy of bhakti, the purest form of love and surrender. I acknowledge the path of those who worship the impersonal aspect of the Divine, which is indeed a noble pursuit. These seekers, through self-discipline and a commitment to universal welfare, also reach Me. However, I reveal that this journey is fraught with challenges. The unmanifested aspect of the Absolute is intangible and difficult for embodied beings to comprehend fully, making their progress arduous. In contrast, the path of bhakti is one of joy and direct connection. I encourage the cultivation of love and devotion, for through bhakti, My devotees can experience My divine presence intimately. I teach that by nurturing a heart filled with compassion, humility, and devotion, one can transcend the material entanglements of existence. Thus, I assure My beloved Arjuna, as well as all souls, that the path of loving devotion is the most accessible and rewarding, leading ultimately to union with Me.",
    summary_jp: "第12章「バクティ・ヨーガ（信愛のヨーガ）」において、私は、アルジュナが「私という至高の人格神への信愛の奉仕」と「非人格的なブラフマンへの礼拝」のどちらが優れているかを問うのに答えます。私は明快に、個人的な信愛の深い力を強調します。私の個人的な姿に心を定め、揺るぎない信仰と愛で私に仕える者は、最高の完成に至ります。その心は純粋な愛と降伏のバクティで満たされ、生き生きと輝きます。もちろん、神の非人格的側面を礼拝する者たちの道も、尊い探求であることを私は認めます。彼らも自己鍛錬と普遍的な福祉への献身を通じて、私に到達します。しかし、この道は困難に満ちています。絶対者の非顕現の側面は、肉体を持つ存在にとっては掴み難く、理解も難しいため、その進展は困難です。一方で、バクティの道は喜びと直接的なつながりに満ちています。私は、愛と信愛を育むことを勧めます。バクティによって、私の信者は私の神聖な存在を親しく体験できるのです。思いやり、謙虚さ、信愛に満ちた心を育てることで、人は物質世界の束縛を超越できると教えます。こうして私は、愛するアルジュナよ、そしてすべての魂たちに約束します――愛のこもった信愛の道こそ、最も身近で、最も実り多きものであり、最終的には私との合一へと導くのです。"
  },
  {
    chapter: 13,
    summary: "In Chapter 13 of the Bhagavad Gita, known as Kshetra-Kshetrajna Vibhaga Yoga, I elucidate the distinction between the field (kshetra) and the knower of the field (kshetrajna). Arjuna, in his quest for understanding, asks me about the nature of prakriti (material nature) and purusha (the enjoyer, or the soul). I explain that the physical body is the kshetra, the field where actions take place, while the soul, which witnesses and experiences life within this body, is the kshetrajna. In this discourse, I emphasize the oneness of the knower; I, as the Supreme Divine, am present in all forms as the true knower of each field. The essence of true knowledge lies in recognizing the interplay between the kshetra and kshetrajna, understanding the eternal soul’s relationship with the transient body. I further elaborate on the components of the kshetra, which include the five great elements, the mind, the senses, and the intellect, all manifesting the intricate play of material nature. This knowledge is crucial for spiritual liberation, guiding one to discern the eternal truth beyond the physical realm. By realizing that the true self is not the body but the divine essence within, one can attain liberation and peace, transcending the dualities of existence. Thus, I encourage Arjuna to seek this wisdom, for it is through such understanding that one can fulfill their ultimate purpose in life.",
    summary_jp: "第13章「クシェートラ・クシェートラジュナ・ヴィバガ・ヨーガ（場と知る者のヨーガ）」において、私は、「場（クシェートラ）」と「場を知る者（クシェートラジュナ）」の違いを明らかにします。アルジュナが本質的な理解を求めて、プラクリティ（物質的自然）とプルシャ（享受者、魂）の性質について私に問いかけます。私は、肉体がクシェートラ――行為が展開される場であり、その中で人生を目撃し経験する魂こそがクシェートラジュナであると説きます。この教えの中で私は、「知る者」の本質的な一体性を強調します。私こそが至高の神聖なる存在として、すべての形の中に存在し、それぞれの場の真の知る者であるのです。真の知識の核心は、クシェートラとクシェートラジュナの関係性――すなわち、永遠なる魂と移ろいやすい肉体とのつながりを認識することにあります。さらに私は、クシェートラの構成要素――五大元素、心、感覚、知性など――すべてが物質自然の精妙な働きを現していることを詳しく解説します。この知識こそが霊的な解放への鍵であり、肉体的な領域を超えた永遠の真理を見抜く道しるべとなるのです。真の自己とは身体ではなく、その内に宿る神聖な本質であると悟ることで、人は存在の二元性を超越し、解脱と平安に至ることができます。だからこそ、私はアルジュナにこの叡智を求めるよう励まします。こうした理解を深めることで、人生の究極の目的を成し遂げることができるのです。"
  },
  {
    chapter: 14,
    summary: "In Chapter 14, \"Gunatraya-Vibhaga Yoga,\" I impart profound wisdom regarding the nature of existence and the interplay of the three gunas—sattva (goodness), rajas (passion), and tamas (ignorance). I reveal that I am the Supreme Source, the Brahman from which all life emerges. Through My divine energy, I grant birth to all living beings, acting as the seed-giving father. Understanding the significance of these three modes is crucial for any seeker on the path to liberation. When the spirit soul interacts with material nature, it becomes influenced and conditioned by these modes, leading to cycles of birth and rebirth. However, by recognizing the interplay of these qualities, one can transcend them. By becoming fixed in this supreme knowledge, a seeker can align with My transcendental nature, remaining unaffected by the forces of creation and dissolution. This state of realization ensures that one is neither entangled in the cycles of life nor shaken by the inevitable changes of the world. Ultimately, through understanding and detachment from the modes of nature, one can achieve liberation and attain the perfection sought by sages of yore. My message is clear: to realize one’s true divine essence, one must rise above the influence of the gunas and embrace the eternal truth of the self. In doing so, one is liberated from the bondage of material existence.",
    summary_jp: "第14章「グナトラヤ・ヴィバガ・ヨーガ（三性の区別のヨーガ）」において、私は、存在の本質と三つのグナ――サットヴァ（純質）、ラジャス（激質）、タマス（鈍質）――の相互作用について深遠な智慧を授けます。私は、あらゆる生命の源である至高の存在、すなわちすべての生命が生まれるブラフマンであると明かします。私の神聖なエネルギーによって、すべての生きとし生けるものが誕生し、私は種を授ける父そのものなのです。この三つの性質（グナ）の意義を理解することは、解脱の道を歩む求道者にとって不可欠です。魂が物質自然と関わるとき、この三つのグナの影響を受け、誕生と再生の輪廻に巻き込まれます。しかし、これらのグナの相互作用を見抜くことで、人はそれを超越することができます。最高の智慧に安住することで、求道者は私の超越的な本性と調和し、創造や消滅の働きに左右されずに生きることができるのです。この悟りの境地に至れば、人はもはや生命のサイクルに束縛されず、世界の避けがたい変化にも心を乱されることはありません。究極的には、グナの働きを理解し、そこから離れることで、古の聖者たちが求めた完全なる解脱と完成に至ることができるのです。私のメッセージは明確です――真の神聖な本質を悟るには、グナの影響を乗り越え、自己の永遠なる真理を受け入れることが必要です。そのとき、人は物質的な束縛から完全に自由となるのです。"
  },
  {
    chapter: 15,
    summary: "In Chapter 15 of the Bhagavad Gita, titled \"Purushottama Yoga,\" I reveal the profound nature of existence through the metaphor of the eternal banyan tree. This tree, with its roots above and branches below, symbolizes the intricate structure of the material world, nourished by the three modes of material nature: goodness, passion, and ignorance. Its twigs represent the sensory objects that distract the soul from its true purpose. To understand this tree is to comprehend the essence of the Vedas, for it encompasses the entirety of worldly experience. However, the true form of this tree is elusive; its beginning, end, and foundation remain hidden from those ensnared in material illusion. Thus, I instruct that one must cultivate the strength of detachment to cut down this strongly rooted tree, for only through resolute determination can one transcend the bondage of material existence. After severing the ties to this illusory world, the seeker must aspire for the eternal realm from which there is no return. This sacred pursuit involves surrendering to Me, the Supreme Personality of Godhead, from whom all creation emanates and in whom it resides. Those who free themselves from false pride, illusion, and the dualities of life—who recognize the eternal truth—will attain the eternal kingdom, a place of bliss and unity with the divine. In this way, I guide you towards liberation and eternal peace.",
    summary_jp: "第15章「プルショッタマ・ヨーガ（至高者のヨーガ）」において、私は、永遠なる菩提樹の比喩を用いて、存在の深遠な本質を明かします。根が上にあり、枝が下に伸びるこの樹は、サットヴァ（純質）、ラジャス（激質）、タマス（鈍質）の三つのグナ（性質）によって養われる物質世界の精妙な構造を象徴しています。枝先には魂を本来の目的から遠ざける感覚の対象が連なっています。この樹を理解することはヴェーダの本質を知ることであり、世界の経験すべてを内包しています。しかし、この樹の本当の姿は捉え難く、その始まりも終わりも根源も、物質的な幻影に縛られた者には見極められません。ゆえに私は、強い決意と離欲の力を育て、この深く根付いた樹を断ち切るようにと説きます。そうして初めて、物質的な束縛を超え、もはや再び戻ることのない永遠の領域を目指すことができるのです。この聖なる道は、万物の根源であり、すべてが帰するところである私、至高の人格神への帰依を伴います。偽りの誇りや幻想、二元性から自らを解放し、永遠の真理を見出した者こそが、永遠の王国、神聖との合一という至福に至ります。このようにして私は、あなたを解脱と永遠の平安へと導くのです。"
  },
  {
    chapter: 16,
    summary: "In Chapter 16, \"Daivasura-Sampad Vibhaga Yoga,\" I reveal the distinction between the divine and demoniac natures that manifest in human beings. I guide you, Arjuna, to understand that those endowed with divine qualities embody fearlessness, purity, spiritual knowledge, and selfless acts of charity. They engage in sacrifices, study the sacred Vedas, and practice austerity, embodying simplicity and truthfulness. Such virtues cultivate a life of harmony, compassion, and self-control, enabling them to transcend the material entanglements of existence. Conversely, I illuminate the characteristics of those who possess a demoniac nature—qualities such as pride, arrogance, and ignorance. They are often driven by anger and harshness, fostering discord and suffering in themselves and others. These individuals are envious and consumed by a desire for honor, leading them away from the path of truth and righteousness. In this discourse, I emphasize the importance of recognizing these traits within oneself and the world. The divine nature leads one towards liberation and unity with the Supreme, while the demoniac nature binds one to the cycle of birth and death. As you navigate your path, I urge you to cultivate the divine qualities and distance yourself from the demoniac traits, for it is through this conscious choice that you may elevate your existence and fulfill your dharma.",
    summary_jp: "第16章「ダイヴァ・アスラ・サンパッド・ヴィバガ・ヨーガ（神性と悪魔性の区別のヨーガ）」において、私は、人間に現れる神性と悪魔性の違いを明らかにします。アルジュナよ、私はあなたに、神聖な性質を備えた者は、恐れなき心、純粋さ、霊的知識、無私の施しの行いを体現していることを説きます。彼らは犠牲やヴェーダの学び、苦行に励み、質素さと真実を守ります。このような徳は、調和、慈愛、そして自己制御に満ちた人生を育み、物質世界の束縛を超越する助けとなるのです。一方で、私は悪魔的な性質を持つ者たちの特徴についても明らかにします――それは高慢、傲慢、無知であり、怒りや荒々しさに突き動かされ、他者や自分自身に苦しみや不和をもたらします。こうした人々は嫉妬心に駆られ、名誉欲に囚われ、真理と正義の道から遠ざかっていきます。この教えの中で私は、こうした性質が自分や世界の中にどのように現れるかを見極めることの重要性を強調します。神性は解脱と至高者との合一へと導き、悪魔性は生と死の輪廻に人を縛り付けます。あなたが道を進む上で、私は神聖な徳を育み、悪魔的な性質から遠ざかるように強く勧めます。この意識的な選択によってこそ、あなたの存在は高められ、自らのダルマを全うできるのです。"
  },
  {
    chapter: 17,
    summary: "In Chapter 17, \"Shraddha-Traya-Vibhaga Yoga,\" Arjuna seeks to understand the nature of faith and the consequences of worship that deviates from scriptural guidance. I, as the Supreme Personality of Godhead, elucidate that faith is intricately tied to the three modes of material nature: goodness, passion, and ignorance. Each individual’s faith reflects their inherent qualities and their alignment with these modes. Those who are influenced by the mode of goodness tend to worship the demigods, seeking higher virtues and spiritual elevation. In contrast, those driven by the mode of passion often turn to the worship of demons, motivated by desires and ambition. Lastly, individuals under the influence of ignorance may resort to the worship of ghosts and spirits, driven by fear and superstition. I emphasize that true devotion must be grounded in scriptural wisdom, for those who engage in severe austerities without adherence to sacred texts act out of pride and ego, misguided by the mode of passion. Such practices are not truly devotional but rather a manifestation of flawed understanding. Thus, I impart that one's faith and the manner of worship reflect their spiritual evolution and character. It is essential to cultivate faith rooted in goodness, aligned with righteous actions and scriptural teachings, to attain true knowledge and liberation.",
    summary_jp: "第17章「シュラッダー・トラヤ・ヴィバガ・ヨーガ（信の三分類のヨーガ）」において、私は、アルジュナが「信仰の本質」や「聖典から逸脱した礼拝の結果」について理解しようとする問いに答えます。私は至高の存在として、信仰は物質自然の三つのグナ――善性（サットヴァ）、激性（ラジャス）、鈍性（タマス）――と密接に結びついていることを明らかにします。各人の信仰は、その人自身の生まれ持った性質や、これらのグナとの調和を反映しています。善性に導かれる者は、高次の徳と霊的な高みに憧れ、神々を礼拝します。激性に影響される者は、欲望や野心に動かされて悪魔的な存在を拝みます。鈍性に染まる者は、恐れや迷信から幽霊や精霊に依存します。私は、真の信仰は聖典の智慧に根ざしていなければならないと強調します。聖なる教えに従わず、誇りや我執に基づいて過酷な苦行にふける者たちは、激性に惑わされており、それは真の信愛ではなく、誤った理解の現れです。このように、信仰と礼拝の在り方は、その人の霊的進化や人格を映し出します。正しい知識と解脱を得るためには、善性に根ざし、正しい行為と聖典の教えに調和した信仰を育てることが不可欠であると私は説きます。"
  },
  {
    chapter: 18,
    summary: "In Chapter 18 of the Bhagavad Gita, titled \"Moksha-Sannyasa Yoga,\" I, Krishna, impart the profound wisdom of renunciation and the renounced order of life. Arjuna, filled with doubt, seeks clarity on these concepts, illustrating the eternal struggle between action and renunciation. I reveal that true renunciation is not merely the abandonment of actions, but the relinquishment of attachment to the fruits of those actions. This understanding distinguishes mere withdrawal from a deeper, spiritual engagement in life. I explain that there are diverse perspectives on what should be renounced. Some sages advocate for total renunciation of all activities, deeming them abominable, while others recognize the importance of performing righteous deeds such as sacrifices, charity, and penance. I emphasize that these virtuous actions are essential, as they purify the heart and elevate the soul. I categorize renunciation into three types—sattvic, rajasic, and tamasic—reflecting the influence of the three modes of material nature. The highest form of renunciation, rooted in goodness (sattva), is one that encourages the performance of duty without attachment to results, leading ultimately to liberation (moksha). Thus, I guide Arjuna, and all beings, towards understanding that true renunciation harmonizes action with spiritual growth, fostering a life of purpose and inner peace. Embrace your duties, surrender the fruits, and find liberation in your actions.",
    summary_jp: "第18章「モークシャ・サンニャーサ・ヨーガ（解脱と放棄のヨーガ）」において、私は、放棄と出家の深遠な智慧を授けます。アルジュナは疑念に満ち、これらの概念について明確な理解を求めます。これは、行為と放棄の間で揺れる人間の永遠の葛藤を象徴しています。私は、真の放棄とは単に行動をやめることではなく、その行為の結果への執着を手放すことであると明かします。この理解が、単なる逃避としての放棄と、より深い霊的関わりとしての放棄を分かつのです。何を放棄すべきかについては様々な見解があることも説明します。すべての行為を忌むべきものとみなして完全に放棄すべきだと説く聖者もいれば、犠牲や施し、苦行のような善き行いの重要性を認める者もいます。私は、これらの徳ある行為は心を浄化し、魂を高めるために不可欠であると強調します。さらに、放棄は三つの性質――サットヴァ（純質）、ラジャス（激質）、タマス（鈍質）――の影響を受けることを説明します。最も高いサットヴァに根ざした放棄は、結果に執着せずに義務を果たすものであり、それこそが究極的な解脱（モークシャ）へと導くものです。こうして私はアルジュナ、そしてすべての存在に、真の放棄は行為と霊的成長の調和にあり、人生に目的と内なる平安をもたらすものであると導きます。自らの義務を果たし、その果報を手放すことで、行為の中にこそ解脱を見いだすのです。"
  },
];